//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sapienza_WiFi.l10n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sapienza_WiFi.l10n.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do a faster than ever authentication and start browsing on the Sapienza University wifi network!
        ///
        ///This app remember your credentials in a secure way, so you do not have to open the browser every time to type them in.
        ///
        ///
        ///This app is not endorsed by Sapienza University. All trademarks and logos are property of their respective owners..
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU ARE ALREADY LOGGED IN..
        /// </summary>
        public static string ALREADY_LOGGEDIN {
            get {
                return ResourceManager.GetString("ALREADY_LOGGEDIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is brought to you by vfede..
        /// </summary>
        public static string BROUGHT_BY {
            get {
                return ResourceManager.GetString("BROUGHT_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU SUCCESSFULLY LOGGED IN..
        /// </summary>
        public static string CONNECTED {
            get {
                return ResourceManager.GetString("CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the form with your credentials for the academic wifi, they will be saved automatically..
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 3G.
        /// </summary>
        public static string DISABLE_3G {
            get {
                return ResourceManager.GetString("DISABLE_3G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle WiFi.
        /// </summary>
        public static string DISABLE_WIFI {
            get {
                return ResourceManager.GetString("DISABLE_WIFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email feedback or suggestions.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable 3G.
        /// </summary>
        public static string ENABLE_3G {
            get {
                return ResourceManager.GetString("ENABLE_3G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable WiFi.
        /// </summary>
        public static string ENABLE_WIFI {
            get {
                return ResourceManager.GetString("ENABLE_WIFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AN ERROR OCCURRED, PLEASE TRY AGAIN..
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already logged in from another device,.
        /// </summary>
        public static string LOGGED_FROM_ANOTHER1 {
            get {
                return ResourceManager.GetString("LOGGED_FROM_ANOTHER1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only 1 logins per user allowed..
        /// </summary>
        public static string LOGGED_FROM_ANOTHER2 {
            get {
                return ResourceManager.GetString("LOGGED_FROM_ANOTHER2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX ATTEMPTS REACHED. PLEASE WAIT 1 MINUTE AND RETRY..
        /// </summary>
        public static string MAX_ATTEMPTS_1 {
            get {
                return ResourceManager.GetString("MAX_ATTEMPTS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX ATTEMPTS REACHED. PLEASE WAIT 5 MINUTE AND RETRY..
        /// </summary>
        public static string MAX_ATTEMPTS_5 {
            get {
                return ResourceManager.GetString("MAX_ATTEMPTS_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap here for more apps..
        /// </summary>
        public static string MORE_APPS {
            get {
                return ResourceManager.GetString("MORE_APPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and review this app.
        /// </summary>
        public static string RATE {
            get {
                return ResourceManager.GetString("RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID number.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string WEB_ERROR {
            get {
                return ResourceManager.GetString("WEB_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not reachable at the moment. Please retry later..
        /// </summary>
        public static string WEB_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("WEB_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi si off..
        /// </summary>
        public static string WIFI_OFF {
            get {
                return ResourceManager.GetString("WIFI_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enable WiFi on your mobile to access the wifi network..
        /// </summary>
        public static string WIFI_OFF_MESSAGE {
            get {
                return ResourceManager.GetString("WIFI_OFF_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRONG USERNAME OR PASSWORD. PLEASE CHECK THEM AND RETRY..
        /// </summary>
        public static string WRONG_CREDENTIALS {
            get {
                return ResourceManager.GetString("WRONG_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sapienza WiFi not found.
        /// </summary>
        public static string WRONG_WIFI {
            get {
                return ResourceManager.GetString("WRONG_WIFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to the Sapienza WiFi network. Open WiFi settings to connect..
        /// </summary>
        public static string WRONG_WIFI_MESSAGE {
            get {
                return ResourceManager.GetString("WRONG_WIFI_MESSAGE", resourceCulture);
            }
        }
    }
}
